version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      VERSION: "latest"
    restart: always
volumes:
  mc:
